-- MySQL Script generated by MySQL Workbench
-- Thu Apr 12 10:05:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema le_bon_potager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema le_bon_potager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `le_bon_potager` DEFAULT CHARACTER SET utf8 ;
USE `le_bon_potager` ;

-- -----------------------------------------------------
-- Table `le_bon_potager`.`T_ROLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `le_bon_potager`.`T_ROLES` ;

CREATE TABLE IF NOT EXISTS `le_bon_potager`.`T_ROLES` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `rolNom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `le_bon_potager`.`T_DEPARTEMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `le_bon_potager`.`T_DEPARTEMENT` ;

CREATE TABLE IF NOT EXISTS `le_bon_potager`.`T_DEPARTEMENT` (
  `id_departement` INT NOT NULL,
  `depLibelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_departement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `le_bon_potager`.`T_VILLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `le_bon_potager`.`T_VILLE` ;

CREATE TABLE IF NOT EXISTS `le_bon_potager`.`T_VILLE` (
  `id_ville` INT NOT NULL AUTO_INCREMENT,
  `vilLibelle` VARCHAR(45) NOT NULL,
  `vilDepartement_id` INT NOT NULL,
  PRIMARY KEY (`id_ville`, `vilDepartement_id`),
  INDEX `fk_T_VILLE_T_DEPARTEMENT1_idx` (`vilDepartement_id` ASC),
  CONSTRAINT `fk_T_VILLE_T_DEPARTEMENT1`
    FOREIGN KEY (`vilDepartement_id`)
    REFERENCES `le_bon_potager`.`T_DEPARTEMENT` (`id_departement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `le_bon_potager`.`T_CODE_POSTAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `le_bon_potager`.`T_CODE_POSTAL` ;

CREATE TABLE IF NOT EXISTS `le_bon_potager`.`T_CODE_POSTAL` (
  `id_code_postal` INT NOT NULL AUTO_INCREMENT,
  `cpLibelle` VARCHAR(45) NOT NULL,
  `cpVille_id` INT NOT NULL,
  PRIMARY KEY (`id_code_postal`, `cpVille_id`),
  INDEX `fk_T_CODE_POSTAL_T_VILLE1_idx` (`cpVille_id` ASC),
  CONSTRAINT `fk_T_CODE_POSTAL_T_VILLE1`
    FOREIGN KEY (`cpVille_id`)
    REFERENCES `le_bon_potager`.`T_VILLE` (`id_ville`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `le_bon_potager`.`T_UTILISATEURS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `le_bon_potager`.`T_UTILISATEURS` ;

CREATE TABLE IF NOT EXISTS `le_bon_potager`.`T_UTILISATEURS` (
  `id_utilisateur` INT NOT NULL AUTO_INCREMENT,
  `utiPseudo` VARCHAR(45) NOT NULL,
  `utiEmail` VARCHAR(254) NOT NULL,
  `utiMdp` VARCHAR(254) NOT NULL,
  `utiValide` TINYINT(1) NOT NULL DEFAULT 0,
  `utiToken` VARCHAR(254) NULL,
  `utilTelAffiche` TINYINT(1) NULL DEFAULT 0,
  `utiTel` VARCHAR(12) NULL,
  `utiDesactive` TINYINT(1) NOT NULL DEFAULT 0,
  `utiDateDesactive` DATETIME NULL,
  `utiDescription` TEXT NULL,
  `utiAdresse` VARCHAR(254) NOT NULL,
  `utiRole_id` INT NOT NULL,
  `utiCp_id` INT NOT NULL,
  `utiAdresseAffiche` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_utilisateur`, `utiRole_id`, `utiCp_id`),
  INDEX `fk_T_UTILISATEURS_T_ROLES1_idx` (`utiRole_id` ASC),
  INDEX `fk_T_UTILISATEURS_T_CODE_POSTAL1_idx` (`utiCp_id` ASC),
  CONSTRAINT `fk_T_UTILISATEURS_T_ROLES1`
    FOREIGN KEY (`utiRole_id`)
    REFERENCES `le_bon_potager`.`T_ROLES` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_UTILISATEURS_T_CODE_POSTAL1`
    FOREIGN KEY (`utiCp_id`)
    REFERENCES `le_bon_potager`.`T_CODE_POSTAL` (`id_code_postal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `le_bon_potager`.`T_CATEGORIE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `le_bon_potager`.`T_CATEGORIE` ;

CREATE TABLE IF NOT EXISTS `le_bon_potager`.`T_CATEGORIE` (
  `id_categorie` INT NOT NULL AUTO_INCREMENT,
  `catNom` VARCHAR(20) NULL,
  PRIMARY KEY (`id_categorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `le_bon_potager`.`T_UNITE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `le_bon_potager`.`T_UNITE` ;

CREATE TABLE IF NOT EXISTS `le_bon_potager`.`T_UNITE` (
  `id_unite` INT NOT NULL AUTO_INCREMENT,
  `uniLibelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_unite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `le_bon_potager`.`T_PRODUITS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `le_bon_potager`.`T_PRODUITS` ;

CREATE TABLE IF NOT EXISTS `le_bon_potager`.`T_PRODUITS` (
  `id_produit` INT NOT NULL AUTO_INCREMENT,
  `proNom` VARCHAR(45) NOT NULL,
  `proCategorie_id` INT NOT NULL,
  `proImg` VARCHAR(254) NULL,
  `proUnite_id` INT NOT NULL,
  PRIMARY KEY (`id_produit`, `proCategorie_id`, `proUnite_id`),
  INDEX `fk_T_PRODUITS_T_CATEGORIE1_idx` (`proCategorie_id` ASC),
  INDEX `fk_T_PRODUITS_T_UNITE1_idx` (`proUnite_id` ASC),
  CONSTRAINT `fk_T_PRODUITS_T_CATEGORIE1`
    FOREIGN KEY (`proCategorie_id`)
    REFERENCES `le_bon_potager`.`T_CATEGORIE` (`id_categorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_PRODUITS_T_UNITE1`
    FOREIGN KEY (`proUnite_id`)
    REFERENCES `le_bon_potager`.`T_UNITE` (`id_unite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `le_bon_potager`.`T_PRODUITS_UTILISATEURS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `le_bon_potager`.`T_PRODUITS_UTILISATEURS` ;

CREATE TABLE IF NOT EXISTS `le_bon_potager`.`T_PRODUITS_UTILISATEURS` (
  `id_produit_utilisateur` INT NOT NULL AUTO_INCREMENT,
  `puVendeur_id` INT NOT NULL,
  `puProduit_id` INT NOT NULL,
  `puCommentaire` TEXT NULL,
  `puQuantite` FLOAT NOT NULL,
  PRIMARY KEY (`id_produit_utilisateur`, `puVendeur_id`, `puProduit_id`),
  INDEX `fk_T_UTILISATEURS_has_T_PRODUITS_T_PRODUITS1_idx` (`puProduit_id` ASC),
  INDEX `fk_T_UTILISATEURS_has_T_PRODUITS_T_UTILISATEURS1_idx` (`puVendeur_id` ASC),
  CONSTRAINT `fk_T_UTILISATEURS_has_T_PRODUITS_T_UTILISATEURS1`
    FOREIGN KEY (`puVendeur_id`)
    REFERENCES `le_bon_potager`.`T_UTILISATEURS` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_UTILISATEURS_has_T_PRODUITS_T_PRODUITS1`
    FOREIGN KEY (`puProduit_id`)
    REFERENCES `le_bon_potager`.`T_PRODUITS` (`id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `le_bon_potager`.`T_RELATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `le_bon_potager`.`T_RELATION` ;

CREATE TABLE IF NOT EXISTS `le_bon_potager`.`T_RELATION` (
  `id_relation` INT NOT NULL AUTO_INCREMENT,
  `relDate` DATETIME NOT NULL DEFAULT NOW(),
  `relQuantite` VARCHAR(45) NOT NULL,
  `relEffectuer` TINYINT(1) NOT NULL DEFAULT 0,
  `relAcheteur_id` INT NOT NULL,
  `relDesactive` TINYINT(1) NOT NULL DEFAULT 0,
  `relDateDesactive` DATETIME NULL,
  `relProduit_utilisateur_id` INT NOT NULL,
  PRIMARY KEY (`id_relation`, `relProduit_utilisateur_id`),
  INDEX `fk_T_RELACTION_T_UTILISATEURS1_idx` (`relAcheteur_id` ASC),
  INDEX `fk_T_RELATION_T_PRODUITS_UTILISATEURS1_idx` (`relProduit_utilisateur_id` ASC),
  CONSTRAINT `fk_T_RELACTION_T_UTILISATEURS1`
    FOREIGN KEY (`relAcheteur_id`)
    REFERENCES `le_bon_potager`.`T_UTILISATEURS` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_RELATION_T_PRODUITS_UTILISATEURS1`
    FOREIGN KEY (`relProduit_utilisateur_id`)
    REFERENCES `le_bon_potager`.`T_PRODUITS_UTILISATEURS` (`id_produit_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `le_bon_potager`.`T_LOGIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `le_bon_potager`.`T_LOGIN` ;

CREATE TABLE IF NOT EXISTS `le_bon_potager`.`T_LOGIN` (
  `logSelector` VARCHAR(255) NOT NULL,
  `logToken` VARCHAR(255) NULL,
  `logExpires` DATETIME NULL,
  `logUtilisateur` INT NOT NULL,
  PRIMARY KEY (`logSelector`, `logUtilisateur`),
  INDEX `fk_T_LOGIN_T_UTILISATEURS1_idx` (`logUtilisateur` ASC),
  CONSTRAINT `fk_T_LOGIN_T_UTILISATEURS1`
    FOREIGN KEY (`logUtilisateur`)
    REFERENCES `le_bon_potager`.`T_UTILISATEURS` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
